// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kspxsvorspdjbkymqrsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzcHhzdm9yc3BkamJreW1xcnN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5Mzc5OTUsImV4cCI6MjA3NDUxMzk5NX0.zmONi1ptaSXyk1Ubt3MLR8jnT79BuImhpivS8Q8xCfc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});